name: mikael_yikum_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_midi_pro: ^3.1.4
  http: ^1.3.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/StateCapitols.txt
  # soundfonts
    - assets/soundfonts/GeneralUser-GS.sf2

  # drum parts
    - assets/drum_parts/drumsStick.png
    - assets/drum_parts/bass_drum.png
    - assets/drum_parts/floor_tom.png
    - assets/drum_parts/Hi-hat.png
    - assets/drum_parts/left_crash.png
    - assets/drum_parts/right_crash.png
    - assets/drum_parts/left_tom.png
    - assets/drum_parts/right_tom.png
    - assets/drum_parts/snare_base.png
    - assets/drum_parts/snare.png
    - assets/drum_parts/tom_mounts.png

    # drum sounds
    - assets/drum_sounds/closed_hi_hat.wav
    - assets/drum_sounds/crash.wav
    - assets/drum_sounds/drum_kick.wav
    - assets/drum_sounds/floor_tom.wav
    - assets/drum_sounds/hi_tom.wav
    - assets/drum_sounds/mid_tom.wav
    - assets/drum_sounds/open_hi_hat.wav
    - assets/drum_sounds/ride.wav
    - assets/drum_sounds/snare.wav